#ifndef FACE_DM_ADMIN_ANGLE_WGS84POSITIONLONGITUDEMEASUREMENTAXIS_LONG
#define FACE_DM_ADMIN_ANGLE_WGS84POSITIONLONGITUDEMEASUREMENTAXIS_LONG

module FACE {
    module DM {
        module admin {
            typedef long Angle_WGS84PositionLongitudeMeasurementAxis_Long;
        };
    };
};

#endif // FACE_DM_ADMIN_ANGLE_WGS84POSITIONLONGITUDEMEASUREMENTAXIS_LONG
