#ifndef FACE_DM_ADMIN_KIND_TEA_KIND_ENUM_ENUMERATION
#define FACE_DM_ADMIN_KIND_TEA_KIND_ENUM_ENUMERATION

module FACE {
    module DM {
        module admin {
            enum Kind_Tea_Kind_Enum_Enumeration {
                JASMINE,
                DARJEELING,
                CHAMOMILE,
                OOLONG,
                EARL_GREY
            };
        };
    };
};

#endif // FACE_DM_ADMIN_KIND_TEA_KIND_ENUM_ENUMERATION
