#ifndef FACE_DM_ADMIN_MASS_FLOAT
#define FACE_DM_ADMIN_MASS_FLOAT

module FACE {
    module DM {
        module admin {
            typedef float mass_Float;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_FLOAT
