#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_LONG
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_LONG

module FACE {
    module DM {
        module admin {
            typedef long Mass_MassMeasurement_Long;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_LONG
