#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_SHORT
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_SHORT

module FACE {
    module DM {
        module admin {
            typedef short Mass_MassMeasurement_Short;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_SHORT
