#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_USHORT
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_USHORT

module FACE {
    module DM {
        module admin {
            typedef unsigned short Mass_MassMeasurement_UShort;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_USHORT
