module FACE {
    module DM {


        module MyModule<typename MyName>  {


            interface MyInterface {

            };
        };

        const long Mylong = 100;


        struct DM;

        struct DM {
            long a;
        };

        struct MyStruct {
            short b;
        };
    };
};
