#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM2
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM2


module FACE {
    module DM {
        module system_driver_interface2 {
            enum SystemEventEnum {
                SYSTEM_DISCOVERED,
                LINK_LOST,
                LINK_ESTABLISHED
            };
        };
    };
};

module AnotherOne {
    enum someJunk {
        value
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM2
