#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM

#include "test2.idl"
#include "test2.idl"

module FACE {
    module DM {
        module system_driver_interface {
            struct Astruct {
                int something;
//                SYSTEM_DISCOVERED,
//                LINK_LOST,
//                LINK_ESTABLISHED
            };

            enum SystemEventEnum {
                VALUE
            };
        };

        enum SystemEventEnum {
            VALUE
        };
    };
};
module AnotherOne {
    enum someJunk {
        value
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENTENUM
