#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_DOUBLE
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_DOUBLE

module FACE {
    module DM {
        module admin {
            typedef double Mass_MassMeasurement_Double;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_DOUBLE
