#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_OCTET
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_OCTET

module FACE {
    module DM {
        module admin {
            typedef octet Mass_MassMeasurement_Octet;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_OCTET
