#ifndef FACE_DM_ADMIN_MASS_MASSMEASUREMENT_CHAR
#define FACE_DM_ADMIN_MASS_MASSMEASUREMENT_CHAR

module FACE {
    module DM {
        module admin {
            typedef char Mass_MassMeasurement_Char;
        };
    };
};

#endif // FACE_DM_ADMIN_MASS_MASSMEASUREMENT_CHAR
