#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_DATALINKCOMMAND
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_DATALINKCOMMAND

#include <FACE/DM/system_driver_interface/SetDatalinkConfigurationCommandData.idl>
#include <FACE/DM/system_driver_interface/DatalinkCommandTypeEnum.idl>

module FACE {
    module DM {
        module system_driver_interface {
            module T_DatalinkCommand {
                union DatalinkCommandUnion;

                union DatalinkCommandUnion swtich (DatalinkCommandTypeEnum) {
                      case SET_CONFIGURATION:
                          SetDatalinkConfigurationCommandData setDatalinkConfiguration;
                };

                struct DatalinkCommand {
                    DatalinkCommandUnion commandData;
                };
            };
            typedef T_DatalinkCommand::DatalinkCommand DatalinkCommand;
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_DATALINKCOMMAND
