#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_ESTABLISHEDLINKEVENTDATA
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_ESTABLISHEDLINKEVENTDATA

#include <FACE/DM/admin/UniqueIdentifier_UniqueID_Unbounded_Text_String.idl>

module FACE {
    module DM {
        module system_driver_interface {
            module T_EstablishedLinkEventData {
                struct EstablishedLinkEventData {
                    UniqueIdentifier_UniqueID_Unbounded_Text_String systemID;
                };
            };
            typedef T_EstablishedLinkEventData::EstablishedLinkEventData EstablishedLinkEventData;
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_ESTABLISHEDLINKEVENTDATA
