#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_LOSTLINKEVENTDATA
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_LOSTLINKEVENTDATA

#include <FACE/DM/admin/UniqueIdentifier_UniqueID_Unbounded_Text_String.idl>

module FACE {
    module DM {
        module system_driver_interface {
            module T_LostLinkEventData {
                struct LostLinkEventData {
                    UniqueIdentifier_UniqueID_Unbounded_Text_String systemID;
                };
            };
            typedef T_LostLinkEventData::LostLinkEventData LostLinkEventData;
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_LOSTLINKEVENTDATA
