#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMDRIVEROPERATIONALSTATEENUM
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMDRIVEROPERATIONALSTATEENUM

module FACE {
    module DM {
        module system_driver_interface {
            enum SystemDriverOperationalStateEnum {
                DISSABLED,
                ENABLED
            };
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMDRIVEROPERATIONALSTATEENUM
