//! Source file: FACE/IOSS/Analog_Injectable.idl

#ifndef FACE_IOSS_ANALOG_INJECTABLE
#define FACE_IOSS_ANALOG_INJECTABLE

#include <FACE/Injectable.idl>
#include <FACE/IOSS/Analog.idl>

module FACE {
  module IOSS {
    module Analog {

      //! Template module instantiation for Analog I/O Service Interface
      module Injectable<
        FACE::IOSS::Analog::IO_Service
      > IO_Service_Injectable;

    }; // module Analog
  }; // module IOSS
}; // module FACE

#endif //! FACE_IOSS_ANALOG_INJECTABLE
