//! Source file: FACE/IOSS/ARINC429_Injectable.idl

#ifndef FACE_IOSS_ARINC429_INJECTABLE
#define FACE_IOSS_ARINC429_INJECTABLE

#include <FACE/Injectable.idl>
#include <FACE/IOSS/ARINC429.idl>

module FACE {
  module IOSS {
    module ARINC429 {

      //! Template module instantiation for ARINC 429 I/O Service Interface
      module Injectable<
        FACE::IOSS::ARINC429::IO_Service
      > IO_Service_Injectable;

    }; // module ARINC429
  }; // module IOSS
}; // module FACE

#endif //! FACE_IOSS_ARINC429_INJECTABLE
