#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_SETDATALINKCONFIGURATIONCOMMANDDATA
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_SETDATALINKCONFIGURATIONCOMMANDDATA

#include <FACE/DM/system_driver_interface/ConfigurationAsXML.idl>

module FACE {
    module DM {
        module system_driver_interface {
            module T_SetDatalinkConfigurationCommandData {
                struct SetDatalinkConfigurationCommandData {
                    ConfigurationAsXML configuration;
                };
            };
            typedef T_SetDatalinkConfigurationCommandData::SetDatalinkConfigurationCommandData SetDatalinkConfigurationCommandData;
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_SETDATALINKCONFIGURATIONCOMMANDDATA
