#ifndef FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENT
#define FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENT

#include <FACE/DM/system_driver_interface/LostLinkEventData.idl>
#include <FACE/DM/system_driver_interface/EstablishedLinkEventData.idl>
#include <FACE/DM/system_driver_interface/NetworkDisclosureEventData.idl>
#include <FACE/DM/system_driver_interface/SystemEventEnum.idl>

module FACE {
    module DM {
        module system_driver_interface {
            module T_SystemEvent {
                union SystemEventDataUnion;

                union SystemEventDataUnion switch (SystemEventEnum) {
                      case LINK_LOST:
                          LostLinkEventData lostLink;
                      case LINK_ESTABLISHED:
                          EstablishedLinkEventData establishedLink;
                      case SYSTEM_DISCOVERED:
                          NetworkDisclosureEventData networkDisclosure;
                };

                struct SystemEvent {
                    SystemEventDataUnion eventData;
                };
            };
            typedef T_SystemEvent::SystemEvent SystemEvent;
        };
    };
};

#endif // FACE_DM_SYSTEM_DRIVER_INTERFACE_SYSTEMEVENT
